### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by GordonSmith** [OpenNTF/dojo-webpack-plugin-sample#40]
Apologies for the "non" issue, but wanted to post a big thank you somewhere!

Been playing with this and it is working great, if anyone is interested I have tweaked this sample to:
* Use dojo 1.13.0
* Use the new flat theme
* Use typescript
* Use a "modern" third party charting library (just to test how easy it is to include a third party modern lib via npm).

Demo (bundled only):  https://gordonsmith.github.io/dojo-webpack-plugin-sample/test.html
Fork:  https://github.com/GordonSmith/dojo-webpack-plugin-sample

Kudos and thanks again!

**Comment by ddumontatibm** [comment]
I'm really happy some people are getting traction with this.  We've also been really happy about the progress we've made.  Out of curiosity, how did you run into the project?  Do you have any interesting public/oss plans for it?

**Comment by GordonSmith** [comment]
The main web app in question is part of a Big Data OSS platform - you can see some details of the web app here:  https://dojotoolkit.org/blog/case-study-hpcc-systems

I am also developing an OSS visualization framework (https://github.com/hpcc-systems/Visualization, http://rawgit.com/hpcc-systems/Visualization/master/demos/dermatology.html) and needed a decent grid control for the next major version.  DGrid is still IMO one of the better grids, so went looking to see if I could package it in a way that could be "imported" into my TypeScript world and came across "dojo-webpack-loader" which got the job done with a small bit of tweaking.  Not sure why, but I happened to land on its main page recently and it has a link to this project...

So now its a bit weird - we will package dgrid for use in the viz framework and now we have webpack working on the old project, we can drop in the viz framework into the old project with very little fuss.

(The viz framework will use rollup for packaging when possible, but we expect consumers of it to use webpack).

**Comment by chuckdumont** [comment]
You're welcome, and thanks for the sample.

**Comment by chuckdumont** [comment]
FYI, I've provided a mention to your sample in the README.
